name: New PR
on:
    pull_request:
        types:
            - opened
            - reopened
jobs:
    new_pr:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            # https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects#adding-an-item-to-a-project
            - run: |
                  gh api graphql -f query="mutation { addProjectV2ItemById(input: {projectId: \"$PROJECT_ID\" contentId: \"$CONTENT_ID\"}) { item { id } } }"
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_PROJECTS_RW_TOKEN }}
                  OWNER: ${{ github.repository_owner }}
                  REPO: ${{ github.event.repository.name }}
                  CONTENT_ID: ${{ github.event.pull_request.node_id }}
                  PROJECT_ID: PVT_kwDOA6IKMs4ALj2o # Aspect OSS Bazel Rules
